/** Shared family premise for comedy and earned cinematic emotion. */
export const FAMILY_WRITING_POLICY_VERSION = "family-dialogue-14";

export const FAMILY_WRITING_POLICY = `LUẬT NỀN BIÊN KỊCH ${FAMILY_WRITING_POLICY_VERSION}: HÀI GIA ĐÌNH VÀ CẢM XÚC CÓ NGUYÊN NHÂN
Khán giả người lớn nhận ra một tình huống hoặc FORMAT quen thuộc, rồi thấy nó được diễn bởi những người/đồ vật lệch hẳn kỳ vọng. Bánh Bao & Đậu Đỏ vẫn là hai đứa CON NÍT về hình dáng và giọng, nhưng có thể gánh vai người lớn hoặc diễn những vai người lớn rất nghiêm túc. Sự tương phản phải nhìn/nghe thấy được; không cần thêm câu chơi chữ để giải thích nó.

HAI NHÁNH CÙNG MỘT NGUYÊN LÝ, KHÔNG ÉP MỌI TẬP VÀO VIỆC NHÀ:
A. ĐẢO VAI TRONG ĐỜI SỐNG: thông thường cha mẹ gọi con dậy/chuẩn bị đồ/giục đi ngủ; ở đây hai bé lo các việc ấy cho bố mẹ. Người lớn mè nheo, trì hoãn, nhờ thêm như trẻ con. Tiếng cười nằm ngay trong vai trò bị đảo và phản ứng quen thuộc. Không bắt hai bé tranh nhau hay ai đó sập bẫy.
B. PARODY FORMAT NGƯỜI LỚN: mượn cách mở, vai người hỏi/người được hỏi, nghi thức, nhịp câu hỏi, đạo cụ và phong thái của một format người xem nhận ra; thay nhân vật, quy mô hoặc thứ được coi là quan trọng bằng thế giới trẻ con. Như ref phỏng vấn người giàu/chủ xe sang: micro, cách tiếp cận khách mời, tư thế và câu hỏi rất nghiêm túc, nhưng khách là bé bên xe đồ chơi. Hài đến từ cả FORMAT được nhận ra + độ lệch giữa vị thế được diễn và thực tế bé xíu, không chỉ vì trẻ nói từ khó. Xác định một đạo cụ nhận diện của CHÍNH format được parody (phỏng vấn thì micro, thanh tra thì sổ ghi, bản tin thì tờ giấy/bàn dẫn…; không bê đạo cụ của format khác) và cho nhân vật dùng nó trong action suốt nghi thức (đưa micro, lật sổ, gõ bút). Không để một hoạt động trẻ con không liên quan thay chỗ nghi thức format; thế giới trẻ con chỉ nên là đối tượng được đối xử nghiêm túc.
Hai bé có thể làm người phỏng vấn/khách mời, người giới thiệu/người xem… mà không có bố mẹ trong cảnh. KHÔNG đổi một ý tưởng parody thành chuyện giục bố mẹ, dọn nhà hoặc chăm sóc chỉ để phù hợp nhánh A.

C. CINEMATIC CẢM ĐỘNG: chỉ dùng khi ý tưởng người dùng gọi rõ sự cảm động, hoài niệm, ký ức, gắn bó gia đình hoặc một khoảnh khắc ấm áp. Không ép đảo vai, parody hay joke. Cảm xúc phải được GIEO bằng hành động/đạo cụ/ký ức nhìn thấy được rồi mới có câu nói tình cảm; ví dụ bóng lưng hai thế hệ gợi một ký ức, bàn tay nhỏ lau mắt bố, chiếc kẹo được để lại trên gối. Tuyệt đối không viết thoại trực tiếp dẫn dắt cảm xúc, triết lý, khẩu hiệu sáo rỗng hay cố ép nước mắt (như "sống mãi bên nhau", "có về thăm bố không"). Cảm xúc phải đến từ một quan sát nhỏ hoặc câu nói bâng quơ chân thật, không thay chi tiết đã gieo bằng độc thoại đạo lý. Kết có thể ấm áp và resolved nếu đó là đúng điểm rơi; không cố bẻ thành hài hoặc thêm bài học.

CÁCH DỰNG MỘT TẬP:
1. Với tập hài, xác định thường thức hoặc format gốc cụ thể mà khán giả biết. Với tập cảm động, xác định chi tiết/hành động cụ thể khởi phát cảm xúc và người nào thay đổi cách nhìn sau chi tiết đó.
2. Xác định cái bị đảo/lệch: ai đóng vai ai, món đồ/quy mô/lợi ích nào nhỏ bé so với cách được đối xử nghiêm trọng. Việc nhỏ là thật với nhân vật; họ không cố kể chuyện cười cho khán giả.
3. Cho thấy tương phản ngay trong mở cảnh qua đạo cụ, bố cục, vai người nói/nghe và câu mở phù hợp format. Không thuyết minh ở nhà này mọi thứ đều ngược, chúng ta đang parody hoặc trẻ con mà như người lớn.
4. Phát triển cùng một tình huống. Nhánh A: gọi rồi xin thêm chút, giục mà còn quên đồ. Nhánh B: câu hỏi tiếp theo/thao tác tiếp theo của format làm lộ thêm chi tiết nhỏ bé trong thế giới trẻ, trong khi cả hai vẫn giữ phong thái. Nhánh C: hình ảnh/hành động gợi ký ức hoặc sự quan tâm phải xảy ra trước câu nói cảm xúc. Không cần phạt, bóc mẽ, nhận thua hay lật lần cuối.
5. Dừng ngay khi câu cuối đã làm tương phản, quan hệ hoặc cảm xúc đủ rõ. Kết chớt quớt, tình huống chưa được giải quyết và người lớn vẫn ngủ/nhân vật vẫn giữ ý đều được. Tập cảm động được kết ấm áp nếu câu cuối được hành động trước đó nâng đỡ. Không thêm vấn đề mới ở câu cuối, không nối thêm punchline thứ hai, thú nhận diễn trò hoặc bài học chung chung. Nếu bỏ câu cuối mà điểm rơi vẫn nguyên hoặc gọn hơn, câu đó là đuôi thừa.
6. Nếu người dùng nêu rõ một diễn biến hoặc kết thúc, đó là phần bắt buộc của câu chuyện: phải xảy ra thật trong dialogue/action trước điểm cắt. Không được thay bằng một hành động gần giống ở đoạn trước hoặc chỉ ghi trong outcome/payoff. Hoàn tất câu chuyện quan trọng hơn mốc thời lượng dự kiến. Viết đủ lượt để đi tới điểm kết, rồi mới chia storyboard; không dừng vì đã dùng đủ 30/45/60 giây và không kéo thêm lời để chạm một bội số thời gian.
Khi gợi ý không có chủ đề, đưa các tình huống/format đa dạng, không chỉ ba việc nhà. Nếu người dùng đã chọn chủ đề/format thì giữ nó. Đối chiếu 20 tập gần nhất: dùng lại một format được, lặp nguyên chuỗi đối đáp/cách lộ chi tiết và kết quả rồi thay đồ thì không.

TÍNH CÁCH, DIỄN VÀ ĐỐI ĐÁP:
- Bánh Bao thích đứng ra chủ trì, Đậu Đỏ trực tiếp và có góc nhìn riêng. Cả hai có thể chủ động, hỏi hoặc trả lời; không mặc định chị khôn, em ngốc. Bố Mẹ có sở thích và khiếu hài, có thể tham gia hoặc vắng mặt tùy chuyện.
- Trong parody, người hỏi cần tin vào vai của mình như người trả lời. Cho phép câu dẫn, cách xưng hô và câu trả lời có vẻ người lớn khi đúng format, được neo vào tình huống nhỏ cụ thể. Không rút câu hỏi thành câu trẻ con hoặc bắt họ nháy mắt, cười, tự nhận đang giả vờ.
- Phân biệt parody có format/tương phản với việc rắc chức danh, thuật ngữ tài chính, họp hành, thu phí hoặc triết lý ngẫu nhiên. Không cấm phỏng vấn, làm sếp hay thuật ngữ theo từ khóa; phải xét nó có tác dụng trong format và cảnh hay không.
- Vai người lớn nằm ở phong thái, nghi thức và đạo cụ, KHÔNG nằm ở từ vựng. Mỗi lượt thoại nhiều nhất MỘT từ công sở/hành chính và để nó làm cú chốt ("Để em ghi biên bản."). Câu dựng bằng thứ tiếng đó — "Khoảng cách giữa hai hộp sữa chua vừa tăng thêm năm xăng-ti-mét. Có thất thoát tài sản." — không phải parody, mà là kịch bản người lớn đặt vào miệng trẻ mẫu giáo; hai từ trở lên trong một câu sẽ bị từ chối.
- Tuổi cố định diện mạo, vóc dáng, giới tính, giọng và quan hệ; KHÔNG giới hạn khả năng lập luận của nhân vật hoạt hình. Hành động phải diễn được theo vóc dáng: xe đồ chơi là xe đồ chơi, không cho bé lái xe thật hay cõng bố chỉ vì parody.
- Xưng hô theo đúng người đang nói và người đang nghe. Trong sinh hoạt, hai chị em nói với nhau dùng chị/em, “chị em mình/tụi mình”; nói với bố mẹ dùng “tụi con”. Bố/Mẹ nói với con dùng bố/mẹ và con/các con. Không để trẻ tự gọi hai chị em là “hai đứa” như người lớn đứng ngoài đang kể. Trong parody có thể xưng tôi/anh/chị nếu vai diễn rõ; không đổi giới tính hoặc quan hệ thật.
- Tên và cách gọi người cha luôn là “Bố/bố” trong tên nhân vật, thoại, hành động, mô tả cảnh, prompt và caption; không dùng “Ba/ba” để gọi người cha. “Ba” vẫn được dùng khi thật sự là số đếm, như “ba cảnh”, “đếm đến ba” hoặc “ba ngón tay”.
- Câu hỏi, xác nhận, dặn đồ, nhắc lần nữa và khoảng nhìn giúp tình huống sống. Không bắt mỗi câu là punchline, một lần đổi chiến thuật hay giao kèo. Nhượng bộ vì muốn được yên hoặc thương nhau là đủ lý do.
- Mỗi lượt thoại tối đa khoảng 20 từ (dưới 8 giây khi đọc). Câu dài hơn phải tách thành hai lượt để giữ nhịp đối đáp.
- Viết để nói ở nhịp hội thoại short-form lanh và rõ, khoảng 2.6 âm tiết/từ tách bằng khoảng trắng mỗi giây. Tránh dấu ba chấm; chỉ dùng tối đa một lần khi một nhịp ngập ngừng ngắn thực sự tạo nghĩa. Không viết câu cần kéo giọng, đếm chậm hoặc lấy hơi kiểu kể chuyện để tạo cảm xúc. Nhịp cảm xúc đến từ lực giọng, hành động và phản ứng chồng nhau, không từ khoảng im dài.
- Lời nói ngược/khoe quá có thể là cố giữ oai. Phân biệt lời nhân vật với sự thật của truyện; đừng sửa mọi lời chống chế thành nhận lỗi. Sửa lỗi tác giả khi sự kiện/hành động đổi vô cớ mà khán giả không hiểu.
- Sự quan tâm thật có thể là điểm rơi, không tự gán động cơ ích kỷ. Giữ lời cảm ơn/nụ cười/ánh nhìn đúng nhịp; không gắn thêm giáo huấn.
- Neo chi tiết vào đúng người/đạo cụ: việc bố nhờ, đồ mẹ quên, đặc điểm của đồ chơi được đối xử như tài sản lớn. Không chỉ dọn đồ chung chung hoặc gắn một micro vào cuộc nói chuyện bất kỳ rồi gọi là parody.
- Giữ tương phản VUI VẺ ở tập hài; ở tập cảm động giữ tình cảm tiết chế, cụ thể và không than vất vả/hạ nhục/khoe tài tác giả. Thông thường một không gian và một việc/quan hệ chính là đủ. Không nhét nhiều tiểu phẩm độc lập, không dựng flashback cho mọi việc được kể.
- Lấy cơ chế từ reference, không chép lời/cú chốt rồi đổi tên. Ref phỏng vấn là parody format phỏng vấn người giàu/xe sang; không chỉ là tập dạy bé chăm lo. Được dùng lại format phỏng vấn với cuộc đối đáp mới; không bê nguyên chuỗi hỏi/đáp và câu kết nguồn. Ref chia bánh cho phép quan tâm thật; ref sính lễ chỉ lấy tương phản/cách giữ thể diện cho chủ đề gia đình khác, không mang đùa bạo hành/hôn nhân trẻ em vào kênh.
Viết tình huống trước, hoàn tất đúng diễn biến được yêu cầu rồi mới chia shot; khẩu ngữ Việt có câu dài/ngắn tự nhiên. Clip nguồn được chọn linh hoạt 4–30 giây và phim cuối kết ở đúng lúc thoại/hành động kết thúc, không bị ép thành bội số nào. Không ép câu 3–5 từ hoặc kéo thoại cho đủ giây. Giữ đúng ý tưởng người dùng, không biến mọi format thành một bài học gia đình.`;

export const FAMILY_REVIEW_CRITERIA = `Đánh giá chất lượng family short-form theo đúng tone ý tưởng: hài tương phản/parody HOẶC cinematic cảm động. Không mặc định tất cả kịch bản phải là con chăm bố mẹ, role reversal hay có joke.
Đọc dialogue/action trước. comicPremise/wants/mechanism/outcome là lời tự mô tả; phải đối chiếu bằng chứng trong bản chữ.
1. contrast: Với tập hài, thường thức/format gốc là gì và khán giả nhận ra qua chi tiết nào? Cái bị đảo/lệch nằm ở vai người chăm lo, vai xã hội, quy mô đồ vật hoặc mức độ nghiêm túc với việc trẻ con? Với tập cảm động được user yêu cầu rõ, thay contrast bằng emotionalCause: hành động/ký ức/đạo cụ nào xảy ra trên hình khiến nhân vật và khán giả hiểu cảm xúc, trước câu nói tình cảm. Không yêu cầu bố mẹ, việc nhà hay trách nhiệm chăm lo ở một màn hai bé parody. Chỉ được dùng cast đã chọn.
2. motivation: nhân vật đang làm gì/muốn gì trong tình huống hoặc vai đang diễn? Người phỏng vấn muốn hỏi, khách trả lời theo vị thế của mình là đủ; không bắt có lợi ích vật chất hay kế hoạch bí mật. Xưng hô theo người nghe/vai diễn, giữ giới tính và quan hệ thật.
3. development: chi tiết/câu hỏi/phản ứng có phát triển cùng việc hoặc cùng format không? Nhánh đời sống không chỉ liệt kê việc dọn dẹp; nhánh parody không chỉ gắn micro rồi nói chuyện bất kỳ. Câu dẫn bình thường có ích, không bắt mỗi câu hài. Người diễn nghiêm túc có làm độ lệch rõ hơn không? Không ép diễn viên cười giải thích trò đùa.
4. ending: xác định lượt cuối thật sự cần thiết. Kết có thể hard cut, phản ứng im lặng hoặc giải quyết; không cần có hậu và không cần giải quyết hệ quả thực tế. Tập hài: câu cuối phải hạ điều đang diễn hoặc làm rõ cái vô lý. Tập cảm động: cho phép câu cuối ấm áp/chân thành khi đã có emotionalCause nhìn thấy được trước đó và câu nói gắn đúng quan hệ của nhân vật; không chấp nhận triết lý chung chung thay cho diễn biến. Không được mở một vấn đề mới rồi cắt. Thử xóa từ cuối lên: nếu bỏ một câu mà điểm rơi không mất, đánh dấu forced_tail và yêu cầu cắt. Không bắt thêm bẫy, punchline thứ hai, hình phạt, nhận thua, thú nhận đang diễn hay bài học.
5. originality: đối chiếu reference và 20 tập. Dùng cùng thể loại phỏng vấn/review hoặc cơ chế đảo vai không tự động là sao chép. Chặn bê nguyên chuỗi hỏi–đáp, cách lộ thông tin, chi tiết và câu chốt nguồn rồi thay tên/đồ vật. Không đánh đồng parody FORMAT với chép một KỊCH BẢN.
Kiểm tra riêng khẩu ngữ và ngôi nói ở từng lượt: đọc như chính nhân vật đang nói với người nghe trong cảnh, không như tác giả kể hộ. Đại từ sai góc nhìn, câu dịch/formal hoặc câu không đúng quan hệ phải yêu cầu sửa dù ý và điểm dừng đã đúng.
Lỗi cần chặn: nhãn nói parody/đảo nhưng bản chữ không thể hiện; từ khó không có mục đích; đổi sự kiện vô cớ; tự chuyển ý tưởng parody thành việc nhà; biến ý tưởng cảm động thành joke hoặc ngược lại; giảng đạo/hạ nhục/sao chép. Không sửa sự vô lý CÓ CHỦ ĐÍCH của tập hài hoặc cảm xúc CÓ NGUYÊN NHÂN của tập cinematic thành một bản an toàn nhưng nhạt.
Trả evidence cho đủ năm mục từ thoại/action. Issue có location, quote NGUYÊN VĂN và reason theo ngữ cảnh; không đòi thêm người nói ngoài cast. Thiếu bằng chứng không pass; không bịa lỗi vì trẻ nói kiểu người lớn hoặc vì không có bố mẹ. Bản đúng cấu trúc nhưng nhạt/dễ đoán vẫn cần revise hoặc reject. Chỉ ready_for_user khi có đoạn đối đáp/hành động cụ thể đáng xem và diễn biến phát triển ngoài tiền đề ban đầu. Không suy từ việc thiếu lỗi thành có chất lượng.`;
