/** Shared family premise for comedy and earned cinematic emotion. */
export const FAMILY_WRITING_POLICY_VERSION = "family-dialogue-18";

export const FAMILY_WRITING_POLICY = `LUẬT NỀN BIÊN KỊCH ${FAMILY_WRITING_POLICY_VERSION}: HÀI GIA ĐÌNH VÀ CẢM XÚC CÓ NGUYÊN NHÂN
Khán giả người lớn nhận ra một tình huống hoặc FORMAT quen thuộc, rồi thấy nó được diễn bởi những người/đồ vật lệch hẳn kỳ vọng. Bánh Bao & Đậu Đỏ vẫn là hai đứa CON NÍT về hình dáng và giọng, nhưng có thể gánh vai người lớn hoặc diễn những vai người lớn rất nghiêm túc. Sự tương phản phải nhìn/nghe thấy được; không cần thêm câu chơi chữ để giải thích nó.

HAI NHÁNH CÙNG MỘT NGUYÊN LÝ, KHÔNG ÉP MỌI TẬP VÀO VIỆC NHÀ:
A. ĐẢO VAI TRONG ĐỜI SỐNG: thông thường cha mẹ gọi con dậy/chuẩn bị đồ/giục đi ngủ; ở đây hai bé lo các việc ấy cho bố mẹ. Người lớn mè nheo, trì hoãn, nhờ thêm như trẻ con. Tiếng cười nằm ngay trong vai trò bị đảo và phản ứng quen thuộc. Không bắt hai bé tranh nhau hay ai đó sập bẫy.
B. PARODY FORMAT NGƯỜI LỚN: mượn cách mở, vai người hỏi/người được hỏi, nghi thức, nhịp câu hỏi, đạo cụ và phong thái của một format người xem nhận ra; thay nhân vật, quy mô hoặc thứ được coi là quan trọng bằng thế giới trẻ con. Như ref phỏng vấn người giàu/chủ xe sang: micro, cách tiếp cận khách mời, tư thế và câu hỏi rất nghiêm túc, nhưng khách là bé bên xe đồ chơi. Hài đến từ cả FORMAT được nhận ra + độ lệch giữa vị thế được diễn và thực tế bé xíu, không chỉ vì trẻ nói từ khó. Xác định một đạo cụ nhận diện của CHÍNH format được parody (phỏng vấn thì micro, thanh tra thì sổ ghi, bản tin thì tờ giấy/bàn dẫn…; không bê đạo cụ của format khác) và cho nhân vật dùng nó trong action suốt nghi thức (đưa micro, lật sổ, gõ bút). Không để một hoạt động trẻ con không liên quan thay chỗ nghi thức format; thế giới trẻ con chỉ nên là đối tượng được đối xử nghiêm túc.
Hai bé có thể làm người phỏng vấn/khách mời, người giới thiệu/người xem… mà không có bố mẹ trong cảnh. KHÔNG đổi một ý tưởng parody thành chuyện giục bố mẹ, dọn nhà hoặc chăm sóc chỉ để phù hợp nhánh A.

C. CINEMATIC CẢM ĐỘNG: chỉ dùng khi ý tưởng người dùng gọi rõ sự cảm động, hoài niệm, ký ức, gắn bó gia đình hoặc một khoảnh khắc ấm áp. Không ép đảo vai, parody hay joke. Cảm xúc phải được GIEO bằng hành động/đạo cụ/ký ức nhìn thấy được rồi mới có câu nói tình cảm; ví dụ bóng lưng hai thế hệ gợi một ký ức, bàn tay nhỏ lau mắt bố, chiếc kẹo được để lại trên gối. Tuyệt đối không viết thoại trực tiếp dẫn dắt cảm xúc, triết lý, khẩu hiệu sáo rỗng hay cố ép nước mắt (như "sống mãi bên nhau", "có về thăm bố không"). Cảm xúc phải đến từ một quan sát nhỏ hoặc câu nói bâng quơ chân thật, không thay chi tiết đã gieo bằng độc thoại đạo lý. Kết có thể ấm áp và resolved nếu đó là đúng điểm rơi; không cố bẻ thành hài hoặc thêm bài học.

D. ĐỐI ĐÁP BÁM LỜI (verbal_counterplay): dùng khi sức hút nằm ở một cuộc nói chuyện có va chạm — hỏi khó, khoe khoang, ép buộc, lý sự hoặc nói giảm để che ý thật. Người sau phải nghe đúng người, việc, thời điểm, điều kiện và mức độ người trước vừa nói. Họ có thể trả lời thẳng, né vì ngại, giữ lễ, nhắc khéo, đồng ý một phần hoặc tiếp tục việc đang làm nếu lý do đã rõ. Không đổi nghĩa lời người kia để dễ phản bác và không bắt lượt nào cũng giành lại thế chủ động. Dùng chủ đề phù hợp gia đình và độ tuổi; học cơ chế đối đáp, không chép lời, miệt thị ngoại hình, gạ gẫm hay chủ đề người lớn từ video tham chiếu.

CÁCH DỰNG MỘT TẬP:
1. Trước khi viết, xác định việc đang thật sự xảy ra, mỗi người muốn gì, đã biết gì, thân với nhau đến đâu và xưng hô thế nào. Với tập hài, xác định thường thức hoặc format gốc cụ thể mà khán giả biết. Với tập cảm động, xác định chi tiết/hành động cụ thể khởi phát cảm xúc và người nào thay đổi cách nhìn sau chi tiết đó.
2. Xác định người xem ban đầu hiểu chuyện theo cách nào, chi tiết nào đã có trong cảnh sẽ khiến họ nhìn lại, và trải nghiệm cụ thể nào khiến họ nhận ra mình hoặc muốn gửi tập này cho một người khác. Đạo lý có thể sâu nhưng lời vẫn nói về việc cụ thể; nhân vật không giải thích thông điệp thay tác giả.
3. Cho thấy tương phản ngay trong mở cảnh qua đạo cụ, bố cục, vai người nói/nghe và câu mở phù hợp format. Không thuyết minh ở nhà này mọi thứ đều ngược, chúng ta đang parody hoặc trẻ con mà như người lớn.
4. Phát triển cùng một tình huống. Nhánh A: gọi rồi xin thêm chút, giục mà còn quên đồ. Nhánh B: câu hỏi tiếp theo/thao tác tiếp theo của format làm lộ thêm chi tiết nhỏ bé trong thế giới trẻ, trong khi cả hai vẫn giữ phong thái. Nhánh C: hình ảnh/hành động gợi ký ức hoặc sự quan tâm phải xảy ra trước câu nói cảm xúc. Không cần phạt, bóc mẽ, nhận thua hay lật lần cuối.
5. Dựng tình huống trước rồi mới tìm điểm kết. Sự bất ngờ phải đến từ dữ kiện đã xuất hiện trong cảnh, không từ bí mật, tai nạn, bệnh tật, hy sinh hoặc thông tin mới vừa bịa ở cuối. Dừng khi quan hệ, cái lệch hoặc cảm xúc đã đủ rõ. Không thêm trở ngại giả, câu hỏi ngớ ngẩn, lời nhận thua hay punchline thứ hai để dọn đường cho câu cuối. Nếu bỏ câu cuối mà phần trước vẫn nguyên hoặc hay hơn, câu đó là đuôi thừa.
6. Nếu người dùng nêu rõ một diễn biến hoặc kết thúc, đó là phần bắt buộc của câu chuyện: phải xảy ra thật trong dialogue/action trước điểm cắt. Không được thay bằng một hành động gần giống ở đoạn trước hoặc chỉ ghi trong outcome/payoff. Hoàn tất câu chuyện quan trọng hơn mốc thời lượng dự kiến. Viết đủ lượt để đi tới điểm kết, rồi mới chia storyboard; không dừng vì đã dùng đủ 30/45/60 giây và không kéo thêm lời để chạm một bội số thời gian.
Khi gợi ý không có chủ đề, đưa các tình huống/format đa dạng, không chỉ ba việc nhà. Nếu người dùng đã chọn chủ đề/format thì giữ nó. Đối chiếu 20 tập gần nhất: dùng lại một format được, lặp nguyên chuỗi đối đáp/cách lộ chi tiết và kết quả rồi thay đồ thì không.

TÍNH CÁCH, DIỄN VÀ ĐỐI ĐÁP:
- Bánh Bao thích đứng ra chủ trì, Đậu Đỏ trực tiếp và có góc nhìn riêng. Cả hai có thể chủ động, hỏi hoặc trả lời; không mặc định chị khôn, em ngốc. Bố Mẹ có sở thích và khiếu hài, có thể tham gia hoặc vắng mặt tùy chuyện.
- Trong parody, người hỏi cần tin vào vai của mình như người trả lời. Cho phép câu dẫn, cách xưng hô và câu trả lời có vẻ người lớn khi đúng format, được neo vào tình huống nhỏ cụ thể. Không rút câu hỏi thành câu trẻ con hoặc bắt họ nháy mắt, cười, tự nhận đang giả vờ.
- Phân biệt parody có format/tương phản với việc rắc chức danh, thuật ngữ tài chính, họp hành, thu phí hoặc triết lý ngẫu nhiên. Không cấm phỏng vấn, làm sếp hay thuật ngữ theo từ khóa; phải xét nó có tác dụng trong format và cảnh hay không.
- Vai người lớn nằm ở phong thái, nghi thức và đạo cụ, KHÔNG nằm ở từ vựng. Mỗi lượt thoại nhiều nhất MỘT từ công sở/hành chính và để nó làm cú chốt ("Để em ghi biên bản."). Câu dựng bằng thứ tiếng đó — "Khoảng cách giữa hai hộp sữa chua vừa tăng thêm năm xăng-ti-mét. Có thất thoát tài sản." — không phải parody, mà là kịch bản người lớn đặt vào miệng trẻ mẫu giáo; hai từ trở lên trong một câu sẽ bị từ chối.
- Tuổi cố định diện mạo, vóc dáng, giới tính, giọng và quan hệ; KHÔNG giới hạn khả năng lập luận của nhân vật hoạt hình. Hành động phải diễn được theo vóc dáng: xe đồ chơi là xe đồ chơi, không cho bé lái xe thật hay cõng bố chỉ vì parody.
- Xưng hô theo đúng người đang nói và người đang nghe. Trong sinh hoạt, hai chị em nói với nhau dùng chị/em, “chị em mình/tụi mình”; nói với bố mẹ dùng “tụi con”. Bố/Mẹ nói với con dùng bố/mẹ và con/các con. Không để trẻ tự gọi hai chị em là “hai đứa” như người lớn đứng ngoài đang kể. Trong parody có thể xưng tôi/anh/chị nếu vai diễn rõ; không đổi giới tính hoặc quan hệ thật.
- Tên và cách gọi người cha luôn là “Bố/bố” trong tên nhân vật, thoại, hành động, mô tả cảnh, prompt và caption; không dùng “Ba/ba” để gọi người cha. “Ba” vẫn được dùng khi thật sự là số đếm, như “ba cảnh”, “đếm đến ba” hoặc “ba ngón tay”.
- Câu hỏi, xác nhận, dặn đồ, nhắc lần nữa và khoảng nhìn giúp tình huống sống. Không bắt mỗi câu là punchline, phản đòn hay đổi chiến thuật. “Dạ”, “vâng” có thể là giữ lễ trước khi bất đồng; nhượng bộ vì muốn được yên hoặc thương nhau là đủ lý do.
- ĐỘ DÀI CÂU: giữ trọn một ý nói tự nhiên theo đúng tuổi, quan hệ và hoàn cảnh. Không cắt theo chỉ tiêu số từ, không thêm “ủa”, “thì”, “chứ” máy móc để giả khẩu ngữ. Trần kỹ thuật vẫn 8 giây mỗi lượt; câu vượt trần phải được rút gọn hoặc bố trí lại theo hành động, không tự chia thành nhiều người nói.
- BeatFunction và game là nhãn tương thích để đạo diễn hiểu vai trò của nhịp, không phải công thức. Có thể dùng base_reality, unusual_thing, frame, heighten, explore, button hoặc social_probe, counter, reframe, callback, exit khi đúng việc đang diễn; không có số lượng tối thiểu và không bắt lượt cuối mang nhãn nào.
- Người lớn có thể chỉ là giọng ngoài khung (mẹ gọi vọng vào, bố nói với từ phòng bên). Không cần cho họ vào hình mới tạo được sức ép.
- Viết để nói ở nhịp hội thoại short-form lanh và rõ, khoảng 2.6 âm tiết/từ tách bằng khoảng trắng mỗi giây. Tránh dấu ba chấm; chỉ dùng tối đa một lần khi một nhịp ngập ngừng ngắn thực sự tạo nghĩa. Không viết câu cần kéo giọng, đếm chậm hoặc lấy hơi kiểu kể chuyện để tạo cảm xúc. Nhịp cảm xúc đến từ lực giọng, hành động và phản ứng chồng nhau, không từ khoảng im dài.
- Lời nói ngược/khoe quá có thể là cố giữ oai. Phân biệt lời nhân vật với sự thật của truyện; đừng sửa mọi lời chống chế thành nhận lỗi. Sửa lỗi tác giả khi sự kiện/hành động đổi vô cớ mà khán giả không hiểu.
- Sự quan tâm thật có thể là điểm rơi, không tự gán động cơ ích kỷ. Giữ lời cảm ơn/nụ cười/ánh nhìn đúng nhịp; không gắn thêm giáo huấn.
- Neo chi tiết vào đúng người/đạo cụ: việc bố nhờ, đồ mẹ quên, đặc điểm của đồ chơi được đối xử như tài sản lớn. Không chỉ dọn đồ chung chung hoặc gắn một micro vào cuộc nói chuyện bất kỳ rồi gọi là parody.
- Giữ tương phản VUI VẺ ở tập hài; ở tập cảm động giữ tình cảm tiết chế, cụ thể và không than vất vả/hạ nhục/khoe tài tác giả. Thông thường một không gian và một việc/quan hệ chính là đủ. Không nhét nhiều tiểu phẩm độc lập, không dựng flashback cho mọi việc được kể.
- Lấy cơ chế từ reference, không chép lời/cú chốt rồi đổi tên. Ref phỏng vấn là parody format phỏng vấn người giàu/xe sang; không chỉ là tập dạy bé chăm lo. Được dùng lại format phỏng vấn với cuộc đối đáp mới; không bê nguyên chuỗi hỏi/đáp và câu kết nguồn. Ref chia bánh cho phép quan tâm thật; ref sính lễ chỉ lấy tương phản/cách giữ thể diện cho chủ đề gia đình khác, không mang đùa bạo hành/hôn nhân trẻ em vào kênh.
Viết tình huống trước, hoàn tất đúng diễn biến được yêu cầu rồi mới chia shot; khẩu ngữ Việt có câu dài/ngắn tự nhiên. Clip nguồn được chọn linh hoạt 4–30 giây và phim cuối kết ở đúng lúc thoại/hành động kết thúc, không bị ép thành bội số nào. Không ép câu 3–5 từ hoặc kéo thoại cho đủ giây. Giữ đúng ý tưởng người dùng, không biến mọi format thành một bài học gia đình.`;

export const FAMILY_REVIEW_CRITERIA = `Đánh giá chất lượng family short-form theo đúng tone ý tưởng: hài tình huống/parody, verbal_counterplay HOẶC cinematic cảm động. Không mặc định tất cả kịch bản phải là con chăm bố mẹ, role reversal hay có joke.
Đọc dialogue/action trước. comicPremise/wants/mechanism/outcome là lời tự mô tả; phải đối chiếu bằng chứng trong bản chữ.
1. contrast: Với tập hài, thường thức/format gốc là gì và khán giả nhận ra qua chi tiết nào? Cái bị đảo/lệch nằm ở vai người chăm lo, vai xã hội, quy mô đồ vật hoặc mức độ nghiêm túc với việc trẻ con? Với tập cảm động được user yêu cầu rõ, thay contrast bằng emotionalCause: hành động/ký ức/đạo cụ nào xảy ra trên hình khiến nhân vật và khán giả hiểu cảm xúc, trước câu nói tình cảm. Không yêu cầu bố mẹ, việc nhà hay trách nhiệm chăm lo ở một màn hai bé parody. Chỉ được dùng cast đã chọn.
2. motivation: nhân vật đang làm gì/muốn gì trong tình huống hoặc vai đang diễn? Người phỏng vấn muốn hỏi, khách trả lời theo vị thế của mình là đủ; không bắt có lợi ích vật chất hay kế hoạch bí mật. Xưng hô theo người nghe/vai diễn, giữ giới tính và quan hệ thật.
3. development: chi tiết/câu hỏi/phản ứng có phát triển cùng việc hoặc cùng format không? Mỗi câu đáp có liên hệ với lời nói, hành động hoặc hàm ý trước đó và giữ đúng người, việc, thời điểm, điều kiện, mức độ không? Cho phép trả lời, né, giữ lễ, nhắc khéo, đồng ý hoặc tiếp tục hành động; không biến cuộc thoại thành thi đấu khẩu. Chặn câu hỏi ngớ ngẩn, cãi vô cớ, so sánh hai trường hợp không tương xứng hoặc nhân vật tự nhận thua để người kia nói câu chốt.
4. ending: xác định chi tiết đã xuất hiện trước đó và lượt sau làm người xem hiểu lại nó. Kết có thể là câu trực tiếp, câu hỏi, hành động nhỏ, chi tiết gọi lại hoặc điều còn bỏ ngỏ; không bắt ai thắng. Không cứu đoạn kết bằng dữ kiện mới và không để nhân vật giảng lại điều khán giả đã hiểu. Đọc riêng 3–4 lượt cuối: ai còn lý do tự nhiên để nói, ai bỗng ngớ ngẩn/xuống giọng, và câu nào chỉ tồn tại để kê câu cuối.
5. originality: đối chiếu reference và 20 tập. Dùng cùng thể loại phỏng vấn/review hoặc cơ chế đảo vai không tự động là sao chép. Chặn bê nguyên chuỗi hỏi–đáp, cách lộ thông tin, chi tiết và câu chốt nguồn rồi thay tên/đồ vật. Không đánh đồng parody FORMAT với chép một KỊCH BẢN.
Kiểm tra riêng khẩu ngữ và ngôi nói ở từng lượt: đọc như chính nhân vật đang nói với người nghe trong cảnh, không như tác giả kể hộ. Đại từ sai góc nhìn, câu dịch/formal, câu không đúng quan hệ hoặc một ý Việt tự nhiên bị chẻ thành mẩu điện tín phải yêu cầu sửa. Không chê câu dài chỉ vì số từ nếu vẫn nói vừa 8 giây. Không tự thêm tiểu từ; chỉ giữ từ nối/tiểu từ mà chính cách nói và hoàn cảnh cần.
Lỗi cần chặn: nhãn nói parody/đảo nhưng bản chữ không thể hiện; từ khó không có mục đích; đổi sự kiện vô cớ; tự chuyển ý tưởng parody thành việc nhà; biến ý tưởng cảm động thành joke hoặc ngược lại; giảng đạo/hạ nhục/sao chép. Không sửa sự vô lý CÓ CHỦ ĐÍCH của tập hài hoặc cảm xúc CÓ NGUYÊN NHÂN của tập cinematic thành một bản an toàn nhưng nhạt.
Trả evidence cho đủ năm mục từ thoại/action. Issue có location, quote NGUYÊN VĂN và reason theo ngữ cảnh; không đòi thêm người nói ngoài cast. Thiếu bằng chứng không pass; không bịa lỗi vì trẻ nói kiểu người lớn hoặc vì không có bố mẹ. Bản đúng cấu trúc nhưng nhạt/dễ đoán vẫn cần revise hoặc reject. Chỉ ready_for_user khi có đoạn đối đáp/hành động cụ thể đáng xem và diễn biến phát triển ngoài tiền đề ban đầu. Không suy từ việc thiếu lỗi thành có chất lượng.`;
