#!/usr/bin/env node

/**
 * Optimize all showcase and template images
 * - Convert PNG → WebP (quality 80)
 * - Resize showcase: 512px (grid display) 
 * - Resize templates: 256px (small previews)
 * - Generate tiny 20px blur placeholders as base64
 * - Output a JSON map of blur placeholders for use in code
 */

import sharp from "sharp";
import { readdirSync, writeFileSync, unlinkSync } from "fs";
import { join, dirname, basename, extname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const publicDir = join(rootDir, "public");

// Config
const SHOWCASE_SIZE = 512;   // showcase images display at ~250px, 512 = 2x for retina
const TEMPLATE_SIZE = 256;   // templates display very small
const WEBP_QUALITY = 80;     // good balance of quality/size
const BLUR_SIZE = 20;        // tiny placeholder for blur-up effect

async function optimizeDir(dir, maxSize, label) {
  const fullDir = join(publicDir, dir);
  const files = readdirSync(fullDir).filter(f => f.endsWith(".png"));
  const blurMap = {};

  console.log(`\n📁 ${label} (${fullDir})`);
  console.log(`   ${files.length} PNG files → WebP @ ${maxSize}px, quality ${WEBP_QUALITY}`);

  for (const file of files) {
    const inputPath = join(fullDir, file);
    const name = basename(file, extname(file));
    const outputPath = join(fullDir, `${name}.webp`);

    try {
      // Get original size
      const origSize = (await sharp(inputPath).toBuffer()).length;

      // Generate optimized WebP
      const webpBuffer = await sharp(inputPath)
        .resize(maxSize, maxSize, { fit: "cover" })
        .webp({ quality: WEBP_QUALITY })
        .toBuffer();

      writeFileSync(outputPath, webpBuffer);

      // Generate blur placeholder (base64)
      const blurBuffer = await sharp(inputPath)
        .resize(BLUR_SIZE, BLUR_SIZE, { fit: "cover" })
        .webp({ quality: 20 })
        .toBuffer();
      
      const blurBase64 = `data:image/webp;base64,${blurBuffer.toString("base64")}`;
      blurMap[name] = blurBase64;

      const savings = ((1 - webpBuffer.length / origSize) * 100).toFixed(0);
      console.log(`   ✅ ${file} → ${name}.webp  ${(origSize/1024).toFixed(0)}KB → ${(webpBuffer.length/1024).toFixed(0)}KB  (-${savings}%)`);

      // Remove original PNG (keep WebP only)
      unlinkSync(inputPath);
    } catch (err) {
      console.error(`   ❌ ${file}: ${err.message}`);
    }
  }

  return blurMap;
}

async function main() {
  console.log("🖼️  Image Optimizer — PNG → WebP + Blur Placeholders\n");

  const showcaseBlurs = await optimizeDir("showcase", SHOWCASE_SIZE, "Showcase Memes");
  const templateBlurs = await optimizeDir("templates", TEMPLATE_SIZE, "Style Templates");

  // Write blur placeholder map
  const allBlurs = { showcase: showcaseBlurs, templates: templateBlurs };
  const blurMapPath = join(rootDir, "src", "lib", "image-blurs.ts");
  
  const tsContent = `// Auto-generated by scripts/optimize-images.mjs
// Tiny blur placeholders for progressive image loading
// Do not edit manually — regenerate with: node scripts/optimize-images.mjs

export const blurPlaceholders: Record<string, Record<string, string>> = ${JSON.stringify(allBlurs, null, 2)} as const;

export function getBlur(category: "showcase" | "templates", name: string): string | undefined {
  return blurPlaceholders[category]?.[name];
}
`;

  writeFileSync(blurMapPath, tsContent);
  console.log(`\n📄 Blur map written to: src/lib/image-blurs.ts`);

  // Summary
  const showcaseDir = join(publicDir, "showcase");
  const templateDir = join(publicDir, "templates");
  const showcaseFiles = readdirSync(showcaseDir).filter(f => f.endsWith(".webp"));
  const templateFiles = readdirSync(templateDir).filter(f => f.endsWith(".webp"));
  
  let totalSize = 0;
  for (const f of showcaseFiles) totalSize += (await sharp(join(showcaseDir, f)).toBuffer()).length;
  for (const f of templateFiles) totalSize += (await sharp(join(templateDir, f)).toBuffer()).length;

  console.log(`\n📊 Total optimized: ${showcaseFiles.length + templateFiles.length} images, ${(totalSize/1024/1024).toFixed(1)}MB`);
  console.log("✨ Done!");
}

main().catch(console.error);
