"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Clapperboard, LoaderCircle, Plus, Trash2, Wand2 } from "lucide-react";
import Sidebar from "@/components/layout/sidebar";
import { useCharacters, useMemes, useProject } from "@/lib/use-store";

type Scene = { characterIds: string[]; speakerCharacterId: string | null; dialogue: string; action: string; setting: string; camera: string; imagePrompt: string; motionPrompt: string; durationSeconds: 5 | 10 | 15 | 30; startImageUrl: string | null; endImageUrl: string | null; followsPrevious: boolean; sourceMode?: "manual" | "ai" };
type Plan = { id: string; version: number; status: string; quote_snapshot?: { totals?: { customerPoints?: number } } | null; video_plan_scenes?: Array<Record<string, unknown>>; cast_snapshot?: Array<{ characterId?: string }> };
const durations = [5, 10, 15, 30] as const;
const emptyScene = (): Scene => ({ characterIds: [], speakerCharacterId: null, dialogue: "", action: "", setting: "", camera: "", imagePrompt: "", motionPrompt: "", durationSeconds: 5, startImageUrl: null, endImageUrl: null, followsPrevious: false, sourceMode: "manual" });

function fromRecord(value: Record<string, unknown>): Scene {
  const duration = Number(value.duration_seconds);
  return { characterIds: Array.isArray(value.cast_snapshot) ? value.cast_snapshot.map((item) => (item as { characterId?: string }).characterId).filter((id): id is string => Boolean(id)) : [], speakerCharacterId: typeof value.speaker_character_id === "string" ? value.speaker_character_id : null, dialogue: typeof value.dialogue === "string" ? value.dialogue : "", action: typeof value.action === "string" ? value.action : "", setting: typeof value.setting === "string" ? value.setting : "", camera: typeof value.camera === "string" ? value.camera : "", imagePrompt: typeof value.image_prompt === "string" ? value.image_prompt : "", motionPrompt: typeof value.motion_prompt === "string" ? value.motion_prompt : "", durationSeconds: (durations.includes(duration as Scene["durationSeconds"]) ? duration : 5) as Scene["durationSeconds"], startImageUrl: typeof value.start_image_url === "string" ? value.start_image_url : null, endImageUrl: typeof value.end_image_url === "string" ? value.end_image_url : null, followsPrevious: value.follows_previous === true, sourceMode: value.source_mode === "ai" ? "ai" : "manual" };
}

export default function MultiSceneVideoPage() {
  const { id: projectRef } = useParams<{ id: string }>();
  const { project } = useProject(projectRef); const { characters } = useCharacters(projectRef); const { memes } = useMemes(projectRef, false);
  const [title, setTitle] = useState("Video nhiều cảnh"); const [brief, setBrief] = useState(""); const [targetDuration, setTargetDuration] = useState<15 | 30 | 60>(30); const [castIds, setCastIds] = useState<string[]>([]); const [scenes, setScenes] = useState<Scene[]>([]); const [selectedScene, setSelectedScene] = useState(0); const [plan, setPlan] = useState<Plan | null>(null); const [busy, setBusy] = useState<"write" | "save" | "quote" | "run" | null>(null); const [error, setError] = useState(""); const [note, setNote] = useState("");
  const total = scenes.reduce((sum, item) => sum + item.durationSeconds, 0); const scene = scenes[selectedScene];
  const imageChoices = useMemo(() => memes.filter((item) => item.image_url).map((item) => ({ id: item.id, url: item.image_url!, label: item.title || "Ảnh thư viện" })), [memes]);
  const updateScene = (index: number, next: Partial<Scene>) => setScenes((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...next, sourceMode: "manual" } : item));
  const toggleCast = (id: string) => setCastIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id].slice(0, 4));

  useEffect(() => { setSelectedScene((current) => Math.min(current, Math.max(0, scenes.length - 1))); }, [scenes.length]);
  useEffect(() => { let active = true; fetch(`/api/projects/${projectRef}/video-plans`).then((response) => response.ok ? response.json() : null).then((payload) => { const latest = payload?.plans?.find((item: Plan) => ["draft", "quoted", "running"].includes(item.status)); if (!active || !latest) return; setPlan(latest); setTitle((latest as Plan & { title?: string }).title || "Video nhiều cảnh"); setBrief((latest as Plan & { brief?: string }).brief || ""); setScenes((latest.video_plan_scenes || []).map(fromRecord)); setCastIds((latest.cast_snapshot || []).map((item: { characterId?: string }) => item.characterId).filter((id: unknown): id is string => typeof id === "string")); }).catch(() => {}); return () => { active = false; }; }, [projectRef]);
  async function waitForAssist(jobId: string) { for (let i = 0; i < 30; i += 1) { const response = await fetch(`/api/projects/${projectRef}/creative-assists/${jobId}`, { cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Không đọc được kết quả AI."); if (json.job.status === "completed") return json.job.result; if (json.job.status === "failed") throw new Error(json.job.error?.code || "AI chưa soạn được kịch bản."); await new Promise((resolve) => window.setTimeout(resolve, 500)); } throw new Error("AI đang xử lý lâu hơn bình thường. Nội dung của bạn vẫn được giữ nguyên."); }
  async function writeScript() { if (!brief.trim()) { setError("Nhập ý tưởng trước để AI viết kịch bản."); return; } setError(""); setNote(""); setBusy("write"); try { const response = await fetch(`/api/projects/${projectRef}/creative-assists`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "video_plan", intent: brief, selectedCharacterIds: castIds, targetDurationSeconds: targetDuration }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Không thể bắt đầu soạn kịch bản."); const result = await waitForAssist(json.jobId); setTitle(result.title || "Video nhiều cảnh"); setScenes(result.scenes.map((item: Scene) => ({ ...item, startImageUrl: null, endImageUrl: null, sourceMode: "ai" }))); setSelectedScene(0); setNote("AI đã viết kịch bản. Bạn có thể sửa từng cảnh trước khi lưu và báo giá."); } catch (reason) { setError(reason instanceof Error ? reason.message : "AI chưa soạn được kịch bản."); } finally { setBusy(null); } }
  async function savePlan() { if (!scenes.length) { setError("Hãy để AI viết kịch bản hoặc thêm ít nhất một cảnh."); return; } setError(""); setBusy("save"); try { const response = await fetch(plan ? `/api/projects/${projectRef}/video-plans/${plan.id}` : `/api/projects/${projectRef}/video-plans`, { method: plan ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, brief, targetDurationSeconds: targetDuration, format: "9:16", resolution: "720p", generateAudio: true, selectedCharacterIds: castIds, expectedVersion: plan?.version, scenes }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Không lưu được kịch bản."); setPlan(json.plan); setNote("Đã lưu bản nháp. Bạn vẫn có thể chỉnh rồi lưu lại."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không lưu được kịch bản."); } finally { setBusy(null); } }
  async function quotePlan() { if (!plan) return savePlan(); setError(""); setBusy("quote"); try { const response = await fetch(`/api/projects/${projectRef}/video-plans/${plan.id}/quote`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedVersion: plan.version }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Không lấy được báo giá."); setPlan((current) => current ? { ...current, status: "quoted", quote_snapshot: { totals: json.quote } } : current); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không lấy được báo giá."); } finally { setBusy(null); } }
  async function runPlan() { if (!plan) return quotePlan(); setError(""); setBusy("run"); try { const response = await fetch(`/api/projects/${projectRef}/video-plans/${plan.id}/run`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedVersion: plan.version }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Không gửi được video."); setPlan((current) => current ? { ...current, status: "running" } : current); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không gửi được video."); } finally { setBusy(null); } }
  const points = plan?.quote_snapshot?.totals?.customerPoints;
  return <div className="flex"><Sidebar projectId={projectRef} projectName={project?.name} /><main className="ml-0 min-h-screen min-w-0 flex-1 p-4 pt-16 lg:ml-56 md:p-8 lg:p-10"><div className="mx-auto max-w-[1360px]">
    <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight th-text-primary">Tạo video</h1><p className="mt-1 text-sm th-text-tertiary">Nhập ý tưởng, AI viết kịch bản và prompt từng cảnh để bạn duyệt trước khi tạo.</p></div><nav className="flex rounded-lg border p-1" style={{ borderColor: "var(--border-primary)" }}><Link href={`/projects/${projectRef}/video`} className="rounded-md px-3 py-2 text-sm font-medium th-text-secondary th-bg-hover">Một clip</Link><span className="rounded-md px-3 py-2 text-sm font-semibold th-bg-accent-light th-text-accent">Nhiều cảnh</span></nav></header>
    <section className="rounded-xl border p-4 sm:p-5" style={{ background: "var(--bg-card)", borderColor: "var(--border-primary)" }}><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_220px]"><label className="text-sm font-semibold th-text-primary">Bạn muốn làm nội dung gì?<textarea value={brief} onChange={(event) => setBrief(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border p-3 text-sm th-bg-input th-text-primary" style={{ borderColor: "var(--border-primary)" }} placeholder="Ví dụ: Bánh Bao và Đậu Đỏ tranh nhau chiếc bánh cuối cùng, kết thúc hài…" /></label><div><p className="text-sm font-semibold th-text-primary">Thời lượng</p><div className="mt-2 flex gap-2">{([15, 30, 60] as const).map((value) => <button key={value} onClick={() => setTargetDuration(value)} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${targetDuration === value ? "th-bg-accent-light th-text-accent th-border-accent" : "th-text-secondary"}`}>{value}s</button>)}</div><button onClick={writeScript} disabled={busy === "write"} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-lg text-sm font-semibold text-white disabled:opacity-60" style={{ background: "var(--accent)" }}>{busy === "write" ? <LoaderCircle className="animate-spin" size={17} /> : <Wand2 size={17} />}{busy === "write" ? "AI đang viết…" : "AI viết kịch bản"}</button></div></div>
    <div className="mt-5 border-t pt-4" style={{ borderColor: "var(--border-primary)" }}><p className="text-sm font-semibold th-text-primary">Nhân vật <span className="font-normal th-text-tertiary">· AI chỉ dùng các nhân vật bạn chọn</span></p><div className="mt-2 flex flex-wrap gap-2">{characters.map((character) => <button key={character.id} onClick={() => toggleCast(character.id)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${castIds.includes(character.id) ? "th-border-accent th-bg-accent-light th-text-accent" : "th-text-secondary"}`}>{character.name}</button>)}</div></div>
    {note && <p className="mt-4 rounded-lg p-3 text-sm th-bg-accent-light th-text-accent">{note}</p>}{error && <p role="alert" className="mt-4 rounded-lg p-3 text-sm th-bg-danger-light th-text-danger">{error}</p>}
    {scenes.length > 0 && <div className="mt-5 grid gap-5 border-t pt-5 lg:grid-cols-[300px_minmax(0,1fr)]" style={{ borderColor: "var(--border-primary)" }}><aside className="rounded-lg border p-2" style={{ borderColor: "var(--border-primary)", background: "var(--bg-secondary)" }}>{scenes.map((item, index) => <button key={index} onClick={() => setSelectedScene(index)} className={`mb-1 flex w-full items-center gap-3 rounded-lg p-2 text-left ${selectedScene === index ? "th-bg-accent-light th-text-accent" : "th-bg-hover th-text-secondary"}`}><span className="flex h-10 w-10 items-center justify-center rounded-md th-bg-card text-xs font-bold">{item.startImageUrl ? <Image src={item.startImageUrl} alt="" width={40} height={40} className="h-10 w-10 rounded-md object-cover" /> : index + 1}</span><span className="min-w-0"><strong className="block truncate text-sm th-text-primary">Cảnh {index + 1}</strong><small className="block truncate">{characters.find((character) => character.id === item.speakerCharacterId)?.name || "Không thoại"} · {item.durationSeconds}s</small></span></button>)}<button onClick={() => { setScenes((current) => [...current, emptyScene()]); setSelectedScene(scenes.length); }} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg border py-2 text-sm font-semibold th-text-primary"><Plus size={15} /> Thêm cảnh</button></aside>
      {scene && <article><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] th-text-accent">Cảnh {selectedScene + 1} · {scene.sourceMode === "ai" ? "AI soạn" : "chỉnh tay"}</p><h2 className="mt-1 text-lg font-semibold th-text-primary">Chỉnh cảnh đang chọn</h2></div><button disabled={scenes.length < 2} onClick={() => setScenes((current) => current.filter((_, index) => index !== selectedScene))} className="rounded-lg p-2 th-text-danger th-bg-hover"><Trash2 size={16} /></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold th-text-secondary">Người nói<select value={scene.speakerCharacterId || ""} onChange={(event) => updateScene(selectedScene, { speakerCharacterId: event.target.value || null })} className="mt-1.5 h-10 w-full rounded-lg border px-2 th-bg-input th-text-primary"><option value="">Không có lời thoại</option>{scene.characterIds.map((id) => <option key={id} value={id}>{characters.find((character) => character.id === id)?.name}</option>)}</select></label><label className="text-xs font-semibold th-text-secondary">Thời lượng<select value={scene.durationSeconds} onChange={(event) => updateScene(selectedScene, { durationSeconds: Number(event.target.value) as Scene["durationSeconds"] })} className="mt-1.5 h-10 w-full rounded-lg border px-2 th-bg-input th-text-primary">{durations.map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Field label="Lời thoại" value={scene.dialogue} onChange={(value) => updateScene(selectedScene, { dialogue: value })} /><Field label="Hành động" value={scene.action} onChange={(value) => updateScene(selectedScene, { action: value })} /><Field label="Bối cảnh" value={scene.setting} onChange={(value) => updateScene(selectedScene, { setting: value })} /></div><details className="mt-4 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-semibold th-text-primary">Xem prompt AI của cảnh</summary><p className="mt-2 text-xs th-text-secondary">Ảnh đầu: {scene.imagePrompt || "Chưa có"}</p><p className="mt-2 text-xs th-text-secondary">Chuyển động: {scene.motionPrompt || "Chưa có"}</p></details><div className="mt-4"><p className="text-sm font-semibold th-text-primary">Ảnh đầu <span className="font-normal th-text-tertiary">· chọn ảnh dự án hoặc sinh từ prompt sau khi duyệt kịch bản</span></p><div className="mt-2 flex gap-2 overflow-x-auto">{imageChoices.slice(0, 12).map((item) => <button key={item.id} onClick={() => updateScene(selectedScene, { startImageUrl: item.url })} className={`relative h-14 w-14 shrink-0 overflow-hidden rounded-lg border ${scene.startImageUrl === item.url ? "th-border-accent" : ""}`}><Image src={item.url} alt={item.label} fill sizes="56px" className="object-cover" /></button>)}</div></div></article>}</div>}
    <div className="sticky bottom-3 mt-6 rounded-xl border p-3" style={{ background: "color-mix(in srgb, var(--bg-card) 94%, transparent)", borderColor: "var(--border-primary)" }}><button disabled={Boolean(busy)} onClick={points ? runPlan : plan ? quotePlan : savePlan} className="flex h-12 w-full items-center justify-center gap-2 rounded-lg text-sm font-semibold text-white disabled:opacity-60" style={{ background: "var(--accent)" }}>{busy ? <LoaderCircle className="animate-spin" size={17} /> : <Clapperboard size={17} />}{points ? `Tạo ${scenes.length} cảnh · ${points.toLocaleString("vi-VN")} điểm` : plan ? "Xem giá video" : scenes.length ? "Lưu kịch bản" : "AI viết kịch bản trước"}</button><p className="mt-2 text-center text-xs th-text-tertiary">{scenes.length ? `${scenes.length} cảnh · ${total}s dự kiến · 720p · âm thanh native` : "Chưa có cảnh nào — AI sẽ soạn bản đầu để bạn duyệt."}</p></div></section>
  </div></main></div>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-semibold th-text-secondary">{label}<textarea value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-24 w-full rounded-lg border p-2 text-sm th-bg-input th-text-primary" /></label>; }
